version: '3.1'

services:
  accessredis:
    image: redis
    networks:
      - mainnet
    deploy:
      placement:
        constraints: [node.role == manager]
  app:
    image: mirbozorgi/shop:1.0.0
    networks:
      - mainnet
    ports:
      - 5050:5050
    environment:
      MIRBOZORGI_APP_PORT: 5050
      MIRBOZORGI_PROFILE: prod
      MIRBOZORGI_APP_LOG: 'false'
      MIRBOZORGI_JPA_INITIALIZATION_MODE: never
      MIRBOZORGI_JPA_DLL_AUTO: none

      MIRBOZORGI_POSTGRES_HOST: //127.0.0.1/postgresql
      MIRBOZORGI_POSTGRES_USER: postgres
      MIRBOZORGI_POSTGRES_PASS: 123



    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
networks:
  mainnet: